name: List books
on:
  workflow_dispatch:
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          python3 -c "
          import json
          data = json.load(open('bible/lsg1910.json'))
          books = sorted(set(v['book_name'] for v in data['verses']))
          print('\n'.join(books))
          "
